# Generated by Django 3.2.8 on 2021-11-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20211116_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
