# Generated by Django 3.2.8 on 2021-11-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211120_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='updated_at',
        ),
    ]
