# Generated by Django 3.2.8 on 2021-11-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211120_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',)},
        ),
    ]
