
version: '3'

services:
  django:
    build:
      context: .
    stdin_open: true # docker run -i
    tty: true
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/CSElite
    command: >
      sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic &&
      gunicorn --bind 0.0.0.0:8000 CS_Elite.wsgi --reload"
    env_file: 
    - ../.env.django
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    env_file: 
    - ../.env.postgresdb
  nginx:
    build:
      ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file: 
    - ../.env.nginx
    ports:
      - 80:80
    depends_on:
      - django
